// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icsovzcgfvhhfvuvdfkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljc292emNnZnZoaGZ2dXZkZmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODczOTEsImV4cCI6MjA2Njk2MzM5MX0.B0ue8L1pfSLQFeDUU8cku13cEZtvrcLiMuhXoXItY-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});